#define     🆕     new
#define     🗄      File:
#define     👌     ;
#define     🏠     return 1;
#define     🔓     {
#define     🔒     }
#define     ▶      >
#define     ◀      <
#define     😡     Kick
#define     😭     Ban
#define     ✅     =
#define     ⛔     -
#define     📏     strlen
#define     🔄     while
#define     👍      +
#define     📢     public
#define     🔙     return
#define     ✍     fwrite
#define     🖨      print
#define     📰     printf
#define     ✔      ==
#define     📖     fopen
#define     📘     fclose
#define     📨     SendClientMessage
#define     💬     ShowPlayerDialog
#define     🏷      Create3DTextLabel
#define     👂      strcmp
  
#define     ⬜      0xFFFFFFAA
